apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_HOST: "{{ .Values.postgresql.host }}"
  POSTGRES_USER: "{{ .Values.postgresql.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.password }}"
  POSTGRES_DB: "{{ .Values.postgresql.database }}"