apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_HOST: "{{ .Values.postgresql.host }}"
  POSTGRES_USER: "{{ .Values.postgresql.user }}"
  POSTGRES_DB: "{{ .Values.postgresql.database }}"